### PR TITLE
fix #353 by adding label column to predict

### LINKED ISSUE #353: MLNet fails on iris
I ran `python runbenchmark.py MLNet test -t iris -f 0 -m docker -s force` and it produced the following failure:
```
train dataset: /input/org/openml/www/datasets/61/dataset_train_0.csv
test dataset: /input/org/openml/www/datasets/61/dataset_test_0.csv
Running cmd `/bench/frameworks/MLNet/lib/mlnet classification --dataset /input/org/openml/www/datasets/61/dataset_train_0.csv --test-dataset /input/org/openml/www/datasets/61/dataset_test_0.csv --train-time 60 --label-col 4 --output /tmp/tmplq81msbb --name 0 --verbosity q --log-file-path /tmp/tmplq81msbb/0/log.txt`
Running cmd `/bench/frameworks/MLNet/lib/mlnet predict --task-type classification --model /tmp/tmplq81msbb/0/0.zip --dataset /input/org/openml/www/datasets/61/dataset_test_0.csv > /tmp/tmplq81msbb/0/prediction.txt`
Error tokenizing data. C error: Expected 1 fields in line 3, saw 3
Traceback (most recent call last):
  File "/bench/amlb/benchmark.py", line 511, in run
    meta_result = self.benchmark.framework_module.run(self._dataset, task_config)
  File "/bench/frameworks/MLNet/__init__.py", line 10, in run
    return run(dataset, config)
  File "/bench/frameworks/MLNet/exec.py", line 82, in run
    prediction_df = pd.read_csv(output_prediction_path, dtype={'PredictedLabel': 'object'})
  File "/bench/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/bench/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/bench/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/bench/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 3
```

Upon closer inspection, it looks like the output file produced by MLNet in this case is actually an error message:

```
"System.ArgumentOutOfRangeException: Column 'label' not found (Parameter 'name')\n",
 '   at Microsoft.ML.DataViewSchema.get_Item(String name)\n',
 '   at Microsoft.ML.ModelBuilder.AutoMLService.ModelInferenceEngine.GetKeyValuesFromColumn(ITransformer model, DataViewSchema schema, String labelColumnName) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/ModelInferenceEngine.cs:line 202\n',
 '   at Microsoft.ML.CLI.Program.<>c.<<Main>b__3_5>d.MoveNext() in /_/src/mlnet/Program.cs:line 180\n',
 '--- End of stack trace from previous location where exception was thrown ---\n', 
 '   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)\n', 
 '   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)\n', 
 '   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()\n', 
 '--- End of stack trace from previous location where exception was thrown ---\n', 
 '   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()\n', 
 '--- End of stack trace from previous location where exception was thrown ---\n', 
 '   at Microsoft.ML.CLI.Program.<>c__DisplayClass3_0.<<Main>b__8>d.MoveNext() in /_/src/mlnet/Program.cs:line 250\n', 
 '--- End of stack trace from previous location where exception was thrown ---\n', 
 '   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()\n', 
'Check out log file for more information: /root/.mlnet/log.txt\n', 
'Exiting ...\n'
```
which understandably can not be read as predictions.

I haven't had too much time to look into this issue yet, but since I have a 3-day weekend I figured I open it anyway for later reference and perhaps @LittleLittleCloud could have a look.

note: I'm trying to reproduce it on AWS, but I am running into some installation issues there ([work in progress](https://github.com/openml/automlbenchmark/tree/fix_mlnet)).

### PR DESCRIPTION
**Pull request by LittleLittleCloud**
### Related issue 
#353 

This fix includes two parts, one in this repo and the other in mlnet repo. I'll update here once the fix in mlnet repo gets in

### CODE REVIEW

**Comment by PGijsbers** [comment]
Will this update break compatibility with older versions of MLNet?

**Comment by LittleLittleCloud** [comment]
@PGijsbers 
Yes it will because ML.Net is a cli tool and this PR changes predict command by adding a new option, so all the previous version will fail.

**Comment by PGijsbers** [comment]
Could you then make the integration backwards compatible by only inserting `--label-col {dataset.target.name}` when using a version that supports it?

**Comment by LittleLittleCloud** [comment]
@PGijsbers 

Is that necessary? ML.Net with a lower version won't work anyway even without that subcommand change. Can we just throw an error when version is too low?

**Comment by PGijsbers** [comment]
> ML.Net with a lower version won't work anyway

I'm sorry, then I think there's just a bit of confusion here. I had assumed that the package worked when it was integrated? Is only a very specific version of ML.Net supported?
I wouldn't mind too much not to have backwards compatibility at this stage (there are no benchmark results yet for ML.Net), but I would prefer to keep it if it's not too big of a change.

**Comment by LittleLittleCloud** [comment]
@PGijsbers 
It did pass all tests when integrated and works well with our benchmark (even for now). But that may be because the test doesn't cover all dataset type. AFAIK all datasets in the test are `.arff` type, and this error only appears when dataset's type is `csv` and it's label name is not `label`. So it's likely that the bug has been there since integration but we just didn't find it.

> Is only a very specific version of ML.Net supported?
This is true even from the very beginning when MLNet being added to the framework. Only MLNet with a version higher than 16.0.0 supports `predict` subcommand and that's the lowest required version. This PR just changes the lowest required version from 16.0.0 to 17.0.0.

**Review by sebhrusen — APPROVED** [review]
that's good to me.
As @PGijsbers mentionned there's no benchmark history with older versions of MLNet.
For future changes however, we should make an effort to avoid backward-incompatible changes.

**Comment by PGijsbers** [comment]
@LittleLittleCloud It looks like `17.0.0` is currently in preview, do you know when it will be released?

**Comment by LittleLittleCloud** [comment]
@PGijsbers 

Soon!

**Comment by LittleLittleCloud** [comment]
@PGijsbers 

I've checked in the fix on the mlnet cli side, feel free to merge in this PR

**Comment by PGijsbers** [comment]
I did not want to merge before the leave because the release wasn't final yet, and then was on leave. Tested locally (through Docker) and it looks good to me.

**Review by PGijsbers — APPROVED** [review]

**Pull request merged**
