### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Innixma**
- Fix minor typo in README
- Enforce `item_id` to always be categorical in time series tasks

### CODE REVIEW

**Comment by PGijsbers** [comment]
Good catch, but shouldn't all instances actually now just be `autogluon`? The exec script has been updated to switch based on dataset type. If that's correct, please update the other instances and then I'll merge :)

**Comment by Innixma** [comment]
Good point, @shchur could you confirm?

**Comment by shchur** [comment]
@Innixma yes, I can confirm. I've opened a PR with changes to `Innixma:patch-1` with updated `README.md` that also includes a small bugfix to ensure that the `item_id` is always parsed as a category. Feel free to move those changes to this PR.

**Comment by Innixma** [comment]
@PGijsbers Updated the PR with @shchur's changes. Should be ready for review/merge.

**Review by PGijsbers — APPROVED** [review]

**Comment by PGijsbers** [comment]
Thanks! :)

**Pull request merged**
