### PR TITLE
Extract prediction time and expose to results file.

### PR DESCRIPTION
**Pull request by sebhrusen**
https://github.com/openml/automlbenchmark/issues/162

Current issues:
- Not able to extract prediction time for frameworks that don't provide a separate  method/call to predict on a dataset:
  - MLPlan (cc: @mwever)
  - AutoWeka

- current support penalizes frameworks whose predict API loads the data from the file system, vs. those who load data separately and for which the prediction duration includes (as expected) *only* the prediction computation. Penalized frameworks:
  - GAMA (cc: @PGijsbers)

### CODE REVIEW

**Comment by mwever** [comment]
So, do I get this correctly that you just want to know how long the finally chosen pipeline takes to make the predictions only? I could easily add this information to the output files of ML-Plan

**Comment by sebhrusen** [comment]
@mwever yes, that's just what we need.
You could probably add this to your statistics file I guess. Thanks!

**Comment by sebhrusen** [comment]
@mwever I'm merging this one for now, please create a new PR once you have this exposed for ML-Plan, thanks.

**Comment by sebhrusen** [comment]
@PGijsbers, I'd like to have this merged soon, ideally before latest framework changes to have everyone aware that we expect being able to obtain prediction time:
- https://github.com/openml/automlbenchmark/pull/183
- https://github.com/openml/automlbenchmark/pull/204
- https://github.com/openml/automlbenchmark/pull/211
- https://github.com/openml/automlbenchmark/pull/203

**Review by PGijsbers — APPROVED** [review]
Looks reasonable to me. As for GAMA, I'll update with a separate PR (if I find the time, benchmark has priority).

**Pull request merged**
