### PR TITLE
ADD FRAMEWORK Auto_ViML

### PR DESCRIPTION
**Pull request by AutoViML**
Please add a description of Auto_ViML which is a popular autoML framework in your list. 
Thanks
Auto_ViML team

### CODE REVIEW

**Review by sebhrusen — CHANGES_REQUESTED** [review]
@AutoViML, we'll be happy to add a description of your framework in the documentation once you help us integrating it the same way it's been done with other frameworks.

**Comment by PGijsbers** [comment]
Hi @AutoViML, thank you for contributing a framework description 🎉 The current frameworks page is outdated, and we are currently discussing if/how we want to make some changes to how we present frameworks. We'll get back to you soon, sorry for the confusion or inconvenience.

**Comment by AutoViML** [comment]
Ok great let me know. What should I do in the meantime?

**Comment by PGijsbers** [comment]
Nothing right now 👍

**Comment by PGijsbers** [comment]
With the new website we decided to not keep documentation on non-integrated frameworks, for now. We would still be happy to assist you integrating AutoVIML into the benchmark ([docs](https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#add-an-automl-framework)).

**Pull request closed without merging**
