### PR TITLE
update mljar-supervised version to 0.6.0

### PR DESCRIPTION
**Pull request by pplonski**
Updating mljar-supervised version to 0.6.0. Is there an option to use the latest version from github or pypi?

### CODE REVIEW

**Comment by PGijsbers** [comment]
Yes, it is possible to specify the version as "latest" ([docs](https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition)). But we prefer a fixed version by default so that it's clear on which version of the packages the benchmark is run and we can ensure it is stable and compatible with the current version of AMLB. This way results are reproducible when running a specific commit of the AMLB. 

It should be easy to run the benchmark against the latest version of a package but I can't find it in the docs (presumably through #144 @sebhrusen)?

We could alternatively also have the frameworks at "latest", and just generate a snapshot benchmark definition every few months with fixed versions. What would you think about that @sebhrusen?

**Comment by sebhrusen** [comment]
@pplonski @PGijsbers for now, it's more reasonable to require a fixed version, user can define a local definition using the latest version as described informally with `autosklearn` in the Framework definitions example: https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition

> We could alternatively also have the frameworks at "latest", and just generate a snapshot benchmark definition every few months with fixed versions.

I like the idea, it would also allow users to (re)run older benchmarks easily as we would add a version of `frameworks.yaml` per quarter let's say. Although, for a minimum of stability and as the frameworks are always read from `frameworks.yaml` by default, I would keep the default `frameworks.yaml` with stable versions. Would you be ok with that?
```
frameworks.yaml  # current stable versions
frameworks_latest.yaml  # all frameworks set to latest (may be pulled directly from `master` branch)
frameworks_2020_Q1.yaml
frameworks_2020_Q2.yaml
...
```

So to use latest for example, user would have to run for example
```
python runbenchmark.py resources/frameworks_latest.yaml#mljarsupervised
```
but the default
```
python runbenchmark.py mljarsupervised
```
would still use the default and stable version from `frameworks.yaml`.
I can create a ticket for that, as you can see, if we want to make the switch easy, it requires some changes in how the `framework` parameter is handled to select the alternative `yaml` definition: either by overloading the syntax on the current param (as we do now for benchmarks), or by adding a new param. Personally, I tend to prefer overloading in this situation...

Well, just realized, it may already work using:
```
python runbenchmark.py mljarsupervised -Xframeworks.definition_file=resources/frameworks_latest.yaml
```
I would need to try it.

**Comment by sebhrusen** [comment]
@pplonski no API change with `0.6.0` right? I guess you tried it and I can trust you on this, this would same me some time, thx!

**Comment by pplonski** [comment]
@sebhrusen yes, no API changes

**Comment by sebhrusen** [comment]
Also moved the discussion regarding `latest` versions and version history to https://github.com/openml/automlbenchmark/issues/160

**Pull request merged**
