### PR TITLE
Update gama

### PR DESCRIPTION
**Pull request by PGijsbers**
Update GAMA so it works with `>=20.2.2` as well as the old supported version(s).
Tested in 'local' mode from a docker container on the `validation` set.

### CODE REVIEW

**Comment by PGijsbers** [comment]
Successfully produced results with `python runbenchmark.py gama validation test -f 0 -m aws -p 7`

**Comment by PGijsbers** [comment]
I wanted to merge it, but trying to run the command again leaves me with no results. It looks like the jobs are possibly executed incorrectly (runtimes are short), but I don't have any debug information other than `Instance initiated shutdown`.

**Comment by sebhrusen** [comment]
mmmh, just tried to run `test` locally (macOS), and seems to work fine except for regression (see error message below):
```text
                  id         task framework constraint fold    result   metric   mode version params                 app_version                  utc  duration  training_duration  predict_duration models_count       seed                                                                    info       acc       auc  balacc   logloss
0  openml.org/t/3913          kc2      GAMA       test    0  0.867965      auc  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:33:48      77.9               54.1               0.0           50  768145286                                                                    None  0.792453  0.867965     0.5  0.487818
1  openml.org/t/3913          kc2      GAMA       test    1  0.929654      auc  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:34:43      54.8               53.2               0.0           50  768145287                                                                    None  0.792453  0.929654     0.5  0.349979
2    openml.org/t/59         iris      GAMA       test    0  0.035099  logloss  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:35:38      55.6               54.1               0.0           50  768145286                                                                    None  1.000000       NaN     1.0  0.035099
3    openml.org/t/59         iris      GAMA       test    1  0.011252  logloss  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:36:34      55.8               54.1               0.0           50  768145287                                                                    None  1.000000       NaN     1.0  0.011252
4  openml.org/t/2295  cholesterol      GAMA       test    0       NaN     rmse  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:37:29      54.9                NaN               NaN               768145286  NoResultError: 'GamaRegressor' object has no attribute 'predict_proba'       NaN       NaN     NaN       NaN
5  openml.org/t/2295  cholesterol      GAMA       test    1       NaN     rmse  local  21.0.0         dev [update_gama, 9181c09]  2021-04-26T11:38:24      55.3                NaN               NaN               768145287  NoResultError: 'GamaRegressor' object has no attribute 'predict_proba'       NaN       NaN     NaN       NaN

```
will try to run validation test (10min/datset) on aws, and confirm.

For the regression issue, you can probably just replace:
```
if is_classification is not None:
```
by
```
if is_classification:
```

**Comment by sebhrusen** [comment]
@PGijsbers just ran 
`python runbenchmark.py gama validation test -f 0 -m aws -p 7`
and results look good:
```
id,task,framework,constraint,fold,result,metric,mode,version,params,app_version,utc,duration,training_duration,predict_duration,models_count,seed,info,acc,auc,balacc,logloss
openml.org/t/2079,eucalyptus,GAMA,test,0,0.656969,logloss,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:05:44,545.9,540.4,0.0,50,798030716,,0.675676,,0.649573,0.656969
openml.org/t/3917,kc1,GAMA,test,0,0.835108,auc,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:06:19,544.9,539.2,0.0,50,798030716,,0.872038,0.835108,0.629452,0.321822
openml.org/t/9910,bioresponse,GAMA,test,0,0.877023,auc,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:06:19,578.2,557.0,0.0,50,798030716,,0.800532,0.877023,0.798393,0.434046
openml.org/t/125920,dresses-sales,GAMA,test,0,0.528736,auc,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:06:28,544.7,539.3,0.0,50,798030716,,0.56,0.528736,0.528736,0.700698
openml.org/t/9950,micro-mass,GAMA,test,0,0.180796,logloss,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:06:40,546.8,539.7,0.0,50,798030716,,0.948276,,0.95,0.180796
openml.org/t/168868,APSFailure,GAMA,test,0,0.977923,auc,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:07:00,593.7,541.7,0.0,48,798030716,,0.973553,0.977923,0.936377,0.859625
openml.org/t/167125,internet-advertisements,GAMA,test,0,0.955057,auc,aws,21.0.0,,"dev [update_gama, 9181c09]",2021-04-26T12:07:01,608.7,543.7,3.3,50,798030716,,0.966463,0.955057,0.889531,0.137993
```
are you sure your `project_repository` property was pointing to your branch in `config.yaml` ?
```
project_repository: https://github.com/openml/automlbenchmark#update_gama
```

Feel free to merge after fixing the regression issue.

**Comment by PGijsbers** [comment]
Thanks for the remarks, fixed! (I had edited the configuration, but forgot I had a config defined in my user directory that overwrote it 🤦‍♂️

**Pull request merged**
