### PR TITLE
Update autogluon to v0.1 API

### PR DESCRIPTION
**Pull request by Innixma**
Updates AutoGluon to use the new v0.1 API (Currently in pre-release).

This PR makes old versions of AutoGluon not able to run (such as v0.0.15) because the API changes are breaking.

If it is important that old versions should still work, I can try to see about adding some try/except checks to determine which API to use.

I have tested this code on the new automlbenchmark study (104 datasets), and AutoGluon_bestquality succeeds on 1h8c constraint with 250GB SSD allocated on 103/104 datasets on all 10 folds (failing dataset is KDDCup09-Upselling due to OOM prior to getting to AutoGluon code).

### CODE REVIEW

**Comment by Innixma** [comment]
AutoGluon v0.1 is planned for release on Feb 8th 2021. If the 2021 Q1 benchmark run hasn't ran by then, I could update this PR to use official v0.1 at that time for use in the 2021 Q1 benchmark.

**Comment by Innixma** [comment]
@PGijsbers AutoGluon v0.1.0 has officially released, so this PR should be ready for testing / review on your end.

**Review by PGijsbers — APPROVED** [review]
Tested with `python runbenchmark.py autogluon validation test -m aws -f 0 -p 7` and all passed.
@sebhrusen what constraints do you normally use?

**Comment by sebhrusen** [comment]
@PGijsbers to test validation datasets, I keep the default constraints (=test, i.e 10min/fold)

**Comment by Innixma** [comment]
A few recommendations for general configs in automlbenchmark:

To avoid out-of-disk errors, I'd recommend that the default disk space allocations for AWS EC2 instances be increased. Currently, they have 16 GB of disk space in `1h8c` config, which isn't a lot to work with on some of the larger datasets that take up over 1 GB of space on their own + the size of the package and dependencies.

Also, the current default disk storage is very slow (hard disk). I suggest switching to `gp2` as the default, which uses SSDs. This is important for AutoGluon because AutoGluon loads and saves to disk many times during fit and inference (not all models are in memory at once to avoid OOM). I noticed AutoGluon inference and training slowed down significantly if using the slow default disk volume.

For my own testing, I used 500 GB of `gp2` space and never ran into disk space issues. I consider this config to be sufficient to accurately assess AutoGluon and other AutoML packages that rely on larger models / disk caching. This could probably be reduced to 250 GB, but I feel that the cost of disk for a short lived EC2 instance is negligible compared to cost of compute.

For example, for 1 hour m5.2xlarge run:

Cost of m5.2xlarge: $0.384/hr
Cost of 250 GB `gp2`: $0.035/hr
Therefore, giving 250 GB to the machines would be less than 10% of the compute cost.

**Comment by PGijsbers** [comment]
Finally had the opportunity to test it also locally on docker, and the validation set passed 👍 so I'll go ahead and merge.

(We had a chat already, but for the public:)
We currently use AWS spot instances, which have lower pricing than indicated. As such using `gp2 ssd` does bring considerable additional costs. As per #187, we do _want_ to add 250GB of SSD storage, but whether or not we get to use them will ultimately depend on our funding and the costs at the time for executing the benchmark.

**Comment by sebhrusen** [comment]
@PGijsbers I wished we hadn't merged this one already: @ledell was trying it on Saturday and had a serious issue: AG did apparently time out on some dataset, however the models created at runtime are always created in some subfolder of the output directory, and are therefore uploaded to s3 if not previously deleted by the `save_artifacts` function.
Because of the timeout, the `save_artifacts` function was not called, the (large amount of) models not deleted, and this ended up with TB of data uploaded to s3 AND downloaded automaticallly on the machine running the benchmark…

Several things will need to be fixed before the next run:
- @Innixma, AG should apply apply the following changes regarding artifacts : write models to a `tmp` folder and move them for export with `save_artifacts` iff required by user.
- I'll review the auto-download to local machine logic to prevent downloading artifacts if not asked explicitely (safety net).

**Comment by Innixma** [comment]
Thanks for the info @sebhrusen . I had assumed this was intended for debugging purposes since it had always functioned in that fashion in automlbenchmark (even before this PR merge), but I agree it isn't a very good experience in general when it takes up significant S3 space.

Regarding the version used for official benchmarking, we can probably use the upcoming v0.1.1 or a pre-release since it drastically reduces the disk usage via an optimization we made to KNN models.

Re the following:

> AG should apply apply the following changes regarding artifacts : write models to a tmp folder and move them for export with save_artifacts iff required by user.

What folder is safe? By default it saves to `output_dir = output_subdir("models", config)`

Are you suggesting it save to `output_dir = 'tmp/'`?

And re 'move them for export', are you sure it's the right approach to move them on disk? Wouldn't it make more sense for the `save_artifacts` function to be able to download from folder A on machine 1 to folder B on machine 2 / S3?

**Comment by sebhrusen** [comment]
@Innixma my concern is not much about disk usage for now but just to prevent models from being uploaded when the user didn't ask for it.
The current logic works, except if AG times out and the app interrupts—or in the worst case kill—the process.
In that case, the existing models remain in `output_dir` and the contract is that everything in output_dir got uploaded to s3.

> Are you suggesting it save to output_dir = 'tmp/'?

you mean "/tmp"? I would use `tempfile.mkdtemp`. If you have a better idea, feel free to suggest.
In the case where models are requested by user, you could also use [this](https://stackoverflow.com/questions/7119630/in-python-how-can-i-get-the-file-system-of-a-given-file-path) to detect the current volume, and pass it to `tempfile.mkdtemp` to be sure that the tmp folder is on the same volume (see. below).

> And re 'move them for export', are you sure it's the right approach to move them on disk? Wouldn't it make more sense for the save_artifacts function to be able to download from folder A on machine 1 to folder B on machine 2 / S3?

When running on AWS all files should be on the same volume, so moving with `shutil.move` will not require any copying and should be almost instant.
Right now I prefer to keep the framework integration code platform-agnostic: it should not know if it's running on aws, docker, and so on...

**Comment by PGijsbers** [comment]
@sebhrusen Sorry 😢 I did not encounter this issue with the validation datasets under test constraints. I wasn't aware other people were still testing it. Because the PR had been open so long, I assumed I was the only one to still test it.

**Comment by sebhrusen** [comment]
@PGijsbers no problem, the fix can be in a separated PR. Just want to make it clear that the fix is needed before the next run.

**Comment by Innixma** [comment]
@sebhrusen I've created #274 to resolve the issue.

**Comment by sebhrusen** [comment]
Thanks a lot @Innixma , will look at it asap.

**Pull request merged**
